# for dev
# docker compose support는 사용하지 않으니 알아서 켜서 사용할 것
# 아래의 명령어를 사용할 것
# docker-compose --env-file .env up -d

services:
  server:
    image: rejs/nearlib:0.1.0
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgis

  postgis:
    image: rejs/pg_bigm:17-postgis
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

#  prometheus:
#    image: prom/prometheus
#    volumes:
#      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - "9030:3000"
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#
#  loki:
#    image: grafana/loki:latest
#    ports:
#      - "3100:3100"
#    volumes:
#      - ./config/loki-config.yml:/etc/loki/loki-config.yml