# for dev
# docker compose support는 사용하지 않으니 알아서 켜서 사용할 것

services:
  postgis:
    image: rejs/pg_bigm:17-postgis
    environment:
      POSTGRES_USER: proxbook_server
      POSTGRES_PASSWORD: proxbook_secret
      POSTGRES_DB: proxbook
    ports:
      - "5432:5432"
