spring:
  application:
    name: nearlib

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory:
              type:  local-heap
            analysis:
              configurer: com.rejs.nearlib.global.hibernate.search.analysis.NgramLuceneAnalysisConfigurerImpl

  flyway:
    enabled: true
    locations: classpath:db/migration/test

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.proxbook.finder : DEBUG
    web: DEBUG
