server:
  servlet:
    context-path: /api
    session:
      cookie:
        path: /
        same-site: none
        secure: true

spring:
  application:
    name: nearlib

  datasource:
    url: ${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.search.backend.type: lucene
      hibernate.search.backend.directory.type: local-filesystem
      hibernate.search.backend.directory.root: app/indexes
      hibernate.search.backend.analysis.configurer: com.rejs.nearlib.global.hibernate.search.analysis.NgramLuceneAnalysisConfigurerImpl

  flyway:
    enabled: true
    locations: classpath:db/migration/dev

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.proxbook.finder : DEBUG
    web: DEBUG

